from .alanine import *
from .amino_acid import *
from .arginine import *
from .asparagine import *
from .aspartic_acid import *
from .cysteine import *
from .glutamic_acid import *
from .glutamine import *
from .glycine import *
from .histidine import *
from .isoleucine import *
from .leucine import *
from .lysine import *
from .methionine import *
from .phenylalanine import *
from .proline import *
from .serine import *
from .threonine import *
from .tryptophan import *
from .tyrosine import *
from .valine import *